name: test-mac
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      # 下载源码
      - name: Checkout code
        uses: actions/checkout@v2

      # 打包构建 Server
      - name: Build Server
        uses: actions/setup-go@v2
        with:
          go-version: "^1.19"

      - run: |
          go run .

