name: test-windows
on:
  push:
    branches:
      - main
jobs:
  test-linux:
    runs-on: ubuntu-latest
    container: docker.io/teamide/build:0.6
    steps:
      # 下载源码
      - name: Checkout code
        uses: actions/checkout@v2

      # 打包构建 Server
      - name: Build Server
        uses: actions/setup-go@v2
        with:
          go-version: "^1.19"

      - run: |
          go run .

  test-mac:
    runs-on: macos-latest
    steps:
      # 下载源码
      - name: Checkout code
        uses: actions/checkout@v2

      # 打包构建 Server
      - name: Build Server
        uses: actions/setup-go@v2
        with:
          go-version: "^1.19"

      - run: |
          go run .
  test-windows:
    runs-on: windows-latest
    steps:
      # 下载源码
      - name: Checkout code
        uses: actions/checkout@v2

      # 打包构建 Server
      - name: Build Server
        uses: actions/setup-go@v2
        with:
          go-version: "^1.19"

      - run: |
          go run .

  build-docker-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          #这里用到了github的secrets功能，避免账户和密码随仓库泄露
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        #导入这个模块来完成自动编译和推送
        uses: docker/build-push-action@v3
        with:
          file: ./build-arm/Dockerfile
          push: true
          #在这里通过加入需要编译的平台和前面配好的QEMU，buildx来达到多平台编译 linux/amd64,linux/arm64,linux/arm
          platforms: linux/arm64
          #指定用户/仓库名
          tags: teamide/build:1.3